config/routes.rb
Rails.application.routes.draw do

  resources :institutes
  
  resources :personnels

  resources :members do 
  resources :consults
	end

   root 'members#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase


end

app/models/institute.rb
class Institute < ActiveRecord::Base

validates :name, :visiting_address, :email_address, :phone, presence: true
validates :email_address, :phone, uniqueness: { case_sensitive: false, message: " already exists in our system" }
validates :phone, numericality: true
validates :email_address, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "format is test@test.com" }
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  before_action :set_institute, only: [:show, :edit, :update, :destroy]

  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
  end

  # GET /institutes/new
  def new
    @institute = Institute.new
  end

  # GET /institutes/1/edit
  def edit
  end

  # POST /institutes
  # POST /institutes.json
  def create
    @institute = Institute.new(institute_params)

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Institute was successfully created.' }
        format.json { render :show, status: :created, location: @institute }
      else
        format.html { render :new }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutes/1
  # PATCH/PUT /institutes/1.json
  def update
    respond_to do |format|
      if @institute.update(institute_params)
        format.html { redirect_to @institute, notice: 'Institute was successfully updated.' }
        format.json { render :show, status: :ok, location: @institute }
      else
        format.html { render :edit }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    @institute.destroy
    respond_to do |format|
      format.html { redirect_to institutes_url, notice: 'Institute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institute
      @institute = Institute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institute_params
      params.require(:institute).permit(:name, :visiting_address, :email_address, :operational_mode, :city, :phone, :remarks)
    end
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_for(@institute) do |f| %>
  <% if @institute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institute.errors.count, "error") %> prohibited this institute from being saved:</h2>

      <ul>
      <% @institute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :visiting_address %><br>
    <%= f.text_field :visiting_address %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :operational_mode %><br>
    <%= f.text_field :operational_mode %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutes/edit.html.erb
<h1>Editing institute</h1>

<%= render 'form' %>

<%= link_to 'Show', @institute %> |
<%= link_to 'Back', institutes_path %>

app/views/institutes/index.html.erb
<h1>Listing institutes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Visiting address</th>
      <th>Email address</th>
      <th>Operational mode</th>
      <th>City</th>
      <th>Phone</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutes.each do |institute| %>
      <tr>
        <td><%= institute.name %></td>
        <td><%= institute.visiting_address %></td>
        <td><%= institute.email_address %></td>
        <td><%= institute.operational_mode %></td>
        <td><%= institute.city %></td>
        <td><%= institute.phone %></td>
        <td><%= institute.remarks %></td>
        <td><%= link_to 'Show', institute %></td>
        <td><%= link_to 'Edit', edit_institute_path(institute) %></td>
        <td><%= link_to 'Destroy', institute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institute', new_institute_path %>

app/views/institutes/new.html.erb
<h1>New institute</h1>

<%= render 'form' %>

<%= link_to 'Back', institutes_path %>

app/views/institutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institute.name %>
</p>

<p>
  <strong>Visiting address:</strong>
  <%= @institute.visiting_address %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @institute.email_address %>
</p>

<p>
  <strong>Operational mode:</strong>
  <%= @institute.operational_mode %>
</p>

<p>
  <strong>City:</strong>
  <%= @institute.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institute.phone %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @institute.remarks %>
</p>

<%= link_to 'Edit', edit_institute_path(@institute) %> |
<%= link_to 'Back', institutes_path %>