config/routes.rb
Rails.application.routes.draw do

  resources :institutes
  
  resources :personnels

  resources :members do 
  resources :consults
	end

   root 'members#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase


end

app/models/personnel.rb
class Personnel < ActiveRecord::Base

validates :name, :duty_station, :specialist, :email_address, :phone, presence: true
validates :email_address, :phone, uniqueness: { case_sensitive: false, message: " already exists in our system" }
validates :phone, numericality: true
 validates :email_address, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "format is test@test.com" }
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  before_action :set_personnel, only: [:show, :edit, :update, :destroy]

  # GET /personnels
  # GET /personnels.json
  def index
    @personnels = Personnel.all
  end

  # GET /personnels/1
  # GET /personnels/1.json
  def show
  end

  # GET /personnels/new
  def new
    @personnel = Personnel.new
  end

  # GET /personnels/1/edit
  def edit
  end

  # POST /personnels
  # POST /personnels.json
  def create
    @personnel = Personnel.new(personnel_params)

    respond_to do |format|
      if @personnel.save
        format.html { redirect_to @personnel, notice: 'Personnel was successfully created.' }
        format.json { render :show, status: :created, location: @personnel }
      else
        format.html { render :new }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnels/1
  # PATCH/PUT /personnels/1.json
  def update
    respond_to do |format|
      if @personnel.update(personnel_params)
        format.html { redirect_to @personnel, notice: 'Personnel was successfully updated.' }
        format.json { render :show, status: :ok, location: @personnel }
      else
        format.html { render :edit }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnels/1
  # DELETE /personnels/1.json
  def destroy
    @personnel.destroy
    respond_to do |format|
      format.html { redirect_to personnels_url, notice: 'Personnel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnel
      @personnel = Personnel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnel_params
      params.require(:personnel).permit(:specialist, :title, :name, :start_date, :email_address, :duty_station, :phone, :remarks)
    end
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/views/personnels/_form.html.erb
<%= form_for(@personnel) do |f| %>
  <% if @personnel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personnel.errors.count, "error") %> prohibited this personnel from being saved:</h2>

      <ul>
      <% @personnel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :specialist %><br>
    <%= f.text_field :specialist %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :duty_station %><br>
    <%= f.text_field :duty_station %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnels/edit.html.erb
<h1>Editing personnel</h1>

<%= render 'form' %>

<%= link_to 'Show', @personnel %> |
<%= link_to 'Back', personnels_path %>

app/views/personnels/index.html.erb
<h1>Listing personnels</h1>

<table>
  <thead>
    <tr>
      <th>Specialist</th>
      <th>Title</th>
      <th>Name</th>
      <th>Start date</th>
      <th>Email address</th>
      <th>Duty station</th>
      <th>Phone</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnels.each do |personnel| %>
      <tr>
        <td><%= personnel.specialist %></td>
        <td><%= personnel.title %></td>
        <td><%= personnel.name %></td>
        <td><%= personnel.start_date %></td>
        <td><%= personnel.email_address %></td>
        <td><%= personnel.duty_station %></td>
        <td><%= personnel.phone %></td>
        <td><%= personnel.remarks %></td>
        <td><%= link_to 'Show', personnel %></td>
        <td><%= link_to 'Edit', edit_personnel_path(personnel) %></td>
        <td><%= link_to 'Destroy', personnel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personnel', new_personnel_path %>

app/views/personnels/new.html.erb
<h1>New personnel</h1>

<%= render 'form' %>

<%= link_to 'Back', personnels_path %>

app/views/personnels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialist:</strong>
  <%= @personnel.specialist %>
</p>

<p>
  <strong>Title:</strong>
  <%= @personnel.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @personnel.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @personnel.start_date %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @personnel.email_address %>
</p>

<p>
  <strong>Duty station:</strong>
  <%= @personnel.duty_station %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @personnel.phone %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @personnel.remarks %>
</p>

<%= link_to 'Edit', edit_personnel_path(@personnel) %> |
<%= link_to 'Back', personnels_path %>