config/routes.rb
Rails.application.routes.draw do

  resources :institutes
  
  resources :personnels

  resources :members do 
  resources :consults
	end

   root 'members#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase


end

app/models/consult.rb
class Consult < ActiveRecord::Base

belongs_to :complain, :polymorphic => true

validates :complain_of_patient, presence: true
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
  before_action :set_consult, only: [:show, :edit, :update, :destroy]

  # GET /consults
  # GET /consults.json
  def index
@complain = find_complain
    @consults = @complain.consults
  end

  # GET /consults/1
  # GET /consults/1.json
  def show
  end

  # GET /consults/new
  def new
    @consult = Consult.new
  end

  # GET /consults/1/edit
  def edit
  end

  # POST /consults
  # POST /consults.json
  def create
@complain = find_complain
    @consult = @complain.consults.new(consult_params)

    respond_to do |format|
      if @consult.save
        format.html { redirect_to :id => nil, notice: 'Consult was successfully created.' }
        format.json { render :show, status: :created, location: @consult }
      else
        format.html { render :index }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consults/1
  # PATCH/PUT /consults/1.json
  def update
@complain = find_complain
    respond_to do |format| 
    
      if @consult = @complain.update(consult_params)
        format.html { redirect_to @consult, notice: 'Consult was successfully updated.' }
        format.json { render :show, status: :ok, location: @consult }
      else
        format.html { render :edit }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consults/1
  # DELETE /consults/1.json
  def destroy
    @consult.destroy
    respond_to do |format|
      format.html { redirect_to consults_url, notice: 'Consult was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consult
      @consult = Consult.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def consult_params
      params.require(:consult).permit(:complain_of_patient, :diagnostic_of_doctor, :prescription_of_doctor, :drugs_delivered, :drugs_delivered_on, :drugs_delivered_by, :complain_id, :complain_type)
    end


private 

def find_complain
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil

end
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/views/consults/_form.html.erb
<%= form_for [@complain, Consult] do |f| %>
  <% if @consult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consult.errors.count, "error") %> prohibited this consult from being saved:</h2>

      <ul>
      <% @consult.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :complain_of_patient %><br>
    <%= f.text_area :complain_of_patient %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_of_doctor %><br>
    <%= f.text_area :diagnostic_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :prescription_of_doctor %><br>
    <%= f.text_area :prescription_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered %><br>
    <%= f.text_field :drugs_delivered %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_on %><br>
    <%= f.date_select :drugs_delivered_on %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_by %><br>
    <%= f.text_field :drugs_delivered_by %>
  </div>
  <div class="field">
    <%= f.label :complain_id %><br>
    <%= f.number_field :complain_id %>
  </div>
  <div class="field">
    <%= f.label :complain_type %><br>
    <%= f.text_field :complain_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consults/edit.html.erb
<h1>Editing consult</h1>

<%= form_for [:id, @consult.id ] do |f| %>
 

  <div class="field">
    <%= f.label :complain_of_patient %><br>
    <%= f.text_area :complain_of_patient %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_of_doctor %><br>
    <%= f.text_area :diagnostic_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :prescription_of_doctor %><br>
    <%= f.text_area :prescription_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered %><br>
    <%= f.text_field :drugs_delivered %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_on %><br>
    <%= f.date_select :drugs_delivered_on %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_by %><br>
    <%= f.text_field :drugs_delivered_by %>
  </div>
  <div class="field">
    <%= f.label :complain_id %><br>
    <%= f.number_field :complain_id %>
  </div>
  <div class="field">
    <%= f.label :complain_type %><br>
    <%= f.text_field :complain_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @consult %> |
<%= link_to 'Back', consults_path %>

app/views/consults/index.html.erb
<h1>Listing consults</h1>

<% @consults.each do | consult |   %>
<div class="consult"> 
<%= consult.complain_of_patient %>
  </div>
<% end  %>


<br>

<%= link_to 'New Consult', new_member_consult_path %>

<br/>
<%= form_for [@complain, Consult.new] do |f| %>
 
  <div class="field">
    <%= f.label :complain_of_patient %><br>
    <%= f.text_area :complain_of_patient %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_of_doctor %><br>
    <%= f.text_area :diagnostic_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :prescription_of_doctor %><br>
    <%= f.text_area :prescription_of_doctor %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered %><br>
    <%= f.text_field :drugs_delivered %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_on %><br>
    <%= f.date_select :drugs_delivered_on %>
  </div>
  <div class="field">
    <%= f.label :drugs_delivered_by %><br>
    <%= f.text_field :drugs_delivered_by %>
  </div>
  <div class="field">
    <%= f.label :complain_id %><br>
    <%= f.number_field :complain_id %>
  </div>
  <div class="field">
    <%= f.label :complain_type %><br>
    <%= f.text_field :complain_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consults/new.html.erb
<h1>New consult</h1>

<%= render 'form' %>

<%= link_to 'Back', member_consults_path %>

app/views/consults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complain of patient:</strong>
  <%= @consult.complain_of_patient %>
</p>

<p>
  <strong>Diagnostic of doctor:</strong>
  <%= @consult.diagnostic_of_doctor %>
</p>

<p>
  <strong>Prescription of doctor:</strong>
  <%= @consult.prescription_of_doctor %>
</p>

<p>
  <strong>Drugs delivered:</strong>
  <%= @consult.drugs_delivered %>
</p>

<p>
  <strong>Drugs delivered on:</strong>
  <%= @consult.drugs_delivered_on %>
</p>

<p>
  <strong>Drugs delivered by:</strong>
  <%= @consult.drugs_delivered_by %>
</p>

<p>
  <strong>Complain:</strong>
  <%= @consult.complain_id %>
</p>

<p>
  <strong>Complain type:</strong>
  <%= @consult.complain_type %>
</p>

<%= link_to 'Edit', edit_member_consult_path(:id, @consult) %> |
<%= link_to 'Back', member_consults_path %>